server:
  port: 8080
  forward-headers-strategy: framework
  servlet: # 한글 깨짐 방지
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  application:
    name: ailways-backend

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      # uri: mongodb://localhost:27017/alpha

  mail:
    host: smtp.gmail.com
    port: 587
    username: ailways714@gmail.com     # ✅ Gmail 계정
    password: ${APP_PW}        # ✅ 앱 비밀번호 (16자리)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_PW}  # 유출 금지
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # 스프링 기본 콜백
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email # 카카오 - 비즈앱 등록시 사용 가능
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # Kakao 응답의 루트 id

app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
    allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO

jwt:
  secret: ${JWT_PW}

ai:
  api:
    url: http://127.0.0.1:8000
    key: dummy-key

  vision: #추가
    enabled: true
    base-url: http://127.0.0.1:8000   # Vision AI 서버가 띄워진 주소/포트

  #ai:
  #  api:
  #    url: https://api.openai.com/v1/chat/completions


  # AI Summary Service Configuration
  # 사용하고자 하는 AI 서비스의 API 엔드포인트 URL을 입력하세요. (예: https://api.openai.com/v1)
  #ai.api.url=https://api.openai.com/v1

  # 발급받은 AI 서비스의 API 키를 입력하세요.
  #ai.api.key=여기에_발급받은_API_키를_입력하세요
